"""
Behavioral Cloning — supervised training on retargeted demos.

Input : (obs, action) pairs generated by rolling out demo joint angles in env
Output: MLP policy checkpoint → used as SAC warm-start

Usage:
    python src/bc_train.py \
        --demos  data/demos/joints_*.npy \
        --xml    /path/to/allegro_cube.xml \
        --out    checkpoints/bc_policy.pt \
        --epochs 100
"""

import argparse
import glob
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

from env import AllegroGraspEnv, ACT_DIM, OBS_DIM


# ── Policy network (same arch as SB3 MlpPolicy default) ──────────────────────

class BCPolicy(nn.Module):
    def __init__(self, obs_dim=OBS_DIM, act_dim=ACT_DIM, hidden=256):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(obs_dim, hidden), nn.ReLU(),
            nn.Linear(hidden, hidden),  nn.ReLU(),
            nn.Linear(hidden, act_dim), nn.Tanh(),  # output ∈ [-1, 1]
        )

    def forward(self, x):
        return self.net(x)


# ── Data collection: roll demo joint angles through env ──────────────────────

def collect_dataset(demo_paths, xml_path):
    obs_list, act_list = [], []

    for path in demo_paths:
        joints = np.load(path)   # (T, 16)
        env    = AllegroGraspEnv(xml_path)
        obs, _ = env.reset()

        for t in range(len(joints) - 1):
            # Action = normalised joint angles ∈ [-1, 1]
            from env import JOINT_MIN, JOINT_MAX
            action = 2.0 * (joints[t] - JOINT_MIN) / (JOINT_MAX - JOINT_MIN) - 1.0
            action = np.clip(action, -1.0, 1.0).astype(np.float32)

            obs_list.append(obs)
            act_list.append(action)

            obs, _, done, _, _ = env.step(action)
            if done:
                break

        env.close()

    obs_t = torch.tensor(np.array(obs_list), dtype=torch.float32)
    act_t = torch.tensor(np.array(act_list), dtype=torch.float32)
    print(f"Dataset: {len(obs_t)} transitions from {len(demo_paths)} demos")
    return TensorDataset(obs_t, act_t)


# ── Training loop ─────────────────────────────────────────────────────────────

def train(dataset, out_path, epochs=100, batch_size=256, lr=3e-4):
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=True)
    policy = BCPolicy()
    opt    = torch.optim.Adam(policy.parameters(), lr=lr)
    loss_fn = nn.MSELoss()

    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    policy.to(device)
    print(f"Training BC on {device} for {epochs} epochs")

    for epoch in range(1, epochs + 1):
        total_loss = 0.0
        for obs_b, act_b in loader:
            obs_b, act_b = obs_b.to(device), act_b.to(device)
            pred = policy(obs_b)
            loss = loss_fn(pred, act_b)
            opt.zero_grad(); loss.backward(); opt.step()
            total_loss += loss.item()

        if epoch % 10 == 0:
            print(f"  Epoch {epoch:3d}/{epochs}  loss={total_loss/len(loader):.5f}")

    torch.save(policy.state_dict(), out_path)
    print(f"BC policy saved → {out_path}")
    return policy


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--demos',  required=True, help='Glob for retargeted .npy files')
    parser.add_argument('--xml',    required=True, help='Allegro+Cube XML path')
    parser.add_argument('--out',    default='checkpoints/bc_policy.pt')
    parser.add_argument('--epochs', type=int, default=100)
    args = parser.parse_args()

    paths = sorted(glob.glob(args.demos))
    if not paths:
        raise FileNotFoundError(f"No files matched: {args.demos}")

    dataset = collect_dataset(paths, args.xml)
    train(dataset, args.out, epochs=args.epochs)


if __name__ == '__main__':
    main()